name: Yoga Academy Festivals
favicon: null
layout_spectrum: 1
typography_spectrum: 0.80903
title: A Journey of Self Discovery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.375
  lightness: 0.6029857699759305
  saturation: 0.9150926184374839
  rhythmicContrast: 0.75
purpose: []
